source("Clean_Format_Data.R")
png(filename='plot2.png',width=480,height=480,units='px')
plot (SetTime,householdpowerdata_Feb$Global_active_power, type = "l",xlab="",ylab="Global Active Power (kilowatts)")
print("Plot 2 Done")
x<-dev.off() 
