source("Clean_Format_Data.R")
png(filename='Plot4.png',width=480,height=480,units='px')
par(mfrow=c(2,2))
plot (SetTime,householdpowerdata_Feb$Global_active_power, type = "l",xlab="",ylab="Global Active Power")
plot (SetTime,householdpowerdata_Feb$Voltage, type = "l",xlab="datetime",ylab="Voltage")
plot(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_2, col="red")
lines(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_3, col="blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
colorName <- c("black","red","blue")
legend("topright", legend = labels, col = colorName ,lty = "solid",bty = "n")
plot (SetTime,householdpowerdata_Feb$Global_reactive_power, type = "l",xlab="datetime",ylab="Global_reactive_power")
print("Plot 4 Done")
x<-dev.off()