source("Clean_Format_Data.R")
png(filename='Plot3.png',width=480,height=480,units='px')
plot(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_2, col="red")
lines(householdpowerdata_Feb$SetTime, householdpowerdata_Feb$Sub_metering_3, col="blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
colorName <- c("black","red","blue")
legend("topright", legend = labels, col = colorName ,lty = "solid")
print("Plot 3 Done")
x<-dev.off()